"""
routes/weather.py — Weather endpoint.

GET /weather/{device_id}  — current + 7-day forecast + farming insight
GET /weather/coords        — direct lat/lon lookup (no farmer profile needed)
"""

import logging

from fastapi import APIRouter, HTTPException, Query, status

from app.schemas import WeatherCurrent, WeatherForecastDay, WeatherOut
from app.services import ai as ai_svc
from app.services import farmer as farmer_svc
from app.services import weather as weather_svc

log = logging.getLogger("agribot.routes.weather")

router = APIRouter(prefix="/weather", tags=["Weather"])


@router.get("/farmer/{device_id}", response_model=WeatherOut)
async def get_weather_for_farmer(device_id: str):
    """
    Fetch weather using the farmer's saved location.
    Returns a farming insight generated by Gemini.
    """
    farmer = await farmer_svc.get_farmer_by_device_id(device_id)
    if not farmer:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Farmer not found")

    lat = farmer.latitude
    lon = farmer.longitude

    if lat is None or lon is None:
        # Try to geocode now if we have enough location info
        if farmer.county:
            coords = await weather_svc.geocode_location(
                ", ".join(filter(None, [farmer.village, farmer.sub_county, farmer.county, "Kenya"]))
            )
            if coords:
                lat, lon = coords
            else:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail="Could not resolve farmer's location. Please update your profile with a valid county.",
                )
        else:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="No location set. Please update your profile first.",
            )

    return await _build_weather_response(
        lat=lat,
        lon=lon,
        location_label=", ".join(filter(None, [farmer.village, farmer.county])) or "Your location",
        primary_crop=farmer.primary_crop,
    )


@router.get("/coords", response_model=WeatherOut)
async def get_weather_by_coords(
    lat: float = Query(..., ge=-90, le=90),
    lon: float = Query(..., ge=-180, le=180),
    location: str = Query("Your location"),
):
    """Direct coords lookup — useful for a location search feature."""
    return await _build_weather_response(lat=lat, lon=lon, location_label=location)


# ---------------------------------------------------------------------------
# Shared builder
# ---------------------------------------------------------------------------

async def _build_weather_response(
    lat: float,
    lon: float,
    location_label: str,
    primary_crop: str | None = None,
) -> WeatherOut:
    try:
        raw = await weather_svc.fetch_weather(lat, lon)
    except Exception as exc:
        log.error("Open-Meteo fetch failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Weather service temporarily unavailable.",
        )

    parsed = weather_svc.parse_weather(raw)
    c = parsed["current"]

    # Build a short weather summary string for Gemini
    weather_summary = (
        f"{c['condition']}, {c['temperature_c']}°C, "
        f"humidity {c['humidity_pct']}%, wind {c['wind_kph']} kph"
    )
    county = location_label.split(",")[0].strip()

    try:
        insight = await ai_svc.get_weather_insight(
            county=county,
            weather_summary=weather_summary,
            primary_crop=primary_crop,
        )
    except Exception as exc:
        log.warning("Weather insight generation failed: %s", exc)
        insight = "Check local conditions before field operations today."

    return WeatherOut(
        location=location_label,
        latitude=lat,
        longitude=lon,
        current=WeatherCurrent(**c),
        forecast=[WeatherForecastDay(**day) for day in parsed["forecast"]],
        farming_insight=insight,
    )
